# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AR Patient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AR Patient
  pod 'Alamofire', '~> 4.9.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.1'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'SWRevealViewController'
  pod 'Firebase/Core'#for fcm
  pod 'Firebase'
  pod 'Firebase/Messaging'#for fcm
  #pod 'Fabric', '~> 1.10.2'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'DGActivityIndicatorView'
  pod 'SFProgressCircle'
  pod "DrawerView"
  pod 'googleapis', :path => '.'
  pod 'SwiftyStoreKit'

end
